schema_version: 1

context:
  version: 0.0.18

package:
  name: sigstore-rekor-types
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sigstore-rekor-types/sigstore_rekor_types-${{ version }}.tar.gz
  sha256: 19aef25433218ebf9975a1e8b523cc84aaf3cd395ad39a30523b083ea7917ec5

build:
  number: 0
  skip: match(python, "<3.8")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools >=75
    - pip
  run:
    - python >=3.8
    - pydantic >=2,<3
    - if: match(python, "<3.9")
      then: typing_extensions

tests:
  - python:
      imports:
        - rekor_types
      pip_check: true

about:
  summary: Python models for Rekor's API types
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/sigstore-rekor-types
  repository: https://github.com/trailofbits/sigstore-rekor-types
  documentation: https://trailofbits.github.io/sigstore-rekor-types/

extra:
  recipe-maintainers:
    - travishathaway
