schema_version: 1

context:
  version: "0.0.6"
  python_min: "3.10"

package:
  name: sigstore-models
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sigstore-models/sigstore_models-${{ version }}.tar.gz
  sha256: c766c09470c2a7e8a4a333c893f07e2001c56a3ff1757b1a246119f53169a849

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.0,<0.10
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.12
    - typing-extensions >=4.14.1

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - sigstore_models
      pip_check: true

about:
  summary: Pydantic based models for Sigstore's protobuf specifications
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/sigstore-models/

extra:
  recipe-maintainers:
    - travishathaway
