schema_version: 1

context:
  maturin_version: "1"
  version: "1.0.5"
  python_min: "3.10"

package:
  name: rfc3161-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rfc3161-client/rfc3161_client-${{ version }}.tar.gz
  sha256: f1a2e32e2a053455cee1ff9b325b88dbc7c66c8882dde60962add92f572df5c5

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin ${{ maturin_version }}.*
  host:
    - maturin ${{ maturin_version }}.*
    - pip
    - python ${{ python_min}}.*
  run:
    - python >=${{ python_min }}
    - cryptography >=43,<47

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - rfc3161_client
      pip_check: true

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/rfc3161-client
  repository: https://github.com/trailofbits/rfc3161-client
  documentation: https://trailofbits.github.io/rfc3161-client/

extra:
  recipe-maintainers:
    - travishathaway
