schema_version: 1

context:
  version: 1.0.5

package:
  name: rfc3161-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rfc3161-client/rfc3161_client-${{ version }}.tar.gz
  sha256: f1a2e32e2a053455cee1ff9b325b88dbc7c66c8882dde60962add92f572df5c5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - maturin >=1.7,<2.0
    - pip
  run:
    - python >=3.9
    - cryptography >=43,<47

tests:
  - python:
      imports:
        - rfc3161_client
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/rfc3161-client
  repository: https://github.com/trailofbits/rfc3161-client
  documentation: https://trailofbits.github.io/rfc3161-client/

extra:
  recipe-maintainers:
    - travishathaway
