schema_version: 1

context:
  version: "4.2.0"
  python_min: "3.10"

package:
  name: sigstore
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sigstore/sigstore-${{ version }}.tar.gz
  sha256: bdbb49a42fd5f0ea6765919adb42ccee7254c482330764d0842eec4e11ad78d7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sigstore = sigstore._cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - cryptography >=42,<47
    - id >=1.1.0
    - if: match(python, "<3.11")
      then: importlib-resources >=5.7,<6.dev0
    - pyasn1 >=0.6,<1.dev0
    - pydantic >=2,<3
    - pyjwt >=2.1
    - pyopenssl >=23.0.0
    - requests
    - rich >=13,<15
    - rfc8785 >=0.1.2,<0.2.dev0
    - rfc3161-client >=1.0.3,<1.1.0
    - sigstore-models ==0.0.6
    - sigstore-rekor-types ==0.0.18
    - tuf >=6.0,<7.dev0
    - platformdirs >=4.2,<5.dev0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - sigstore
      pip_check: true
  - requirements:
      run:
        - pip
        - python
    script:
      - sigstore --help

about:
  summary: A tool for signing Python package distributions
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/sigstore/
  repository: https://github.com/sigstore/sigstore-python
  documentation: https://sigstore.github.io/sigstore-python/

extra:
  recipe-maintainers:
    - travishathaway
