schema_version: 1

context:
  version: 6.0.0

package:
  name: tuf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tuf/tuf-${{ version }}.tar.gz
  sha256: 9eed0f7888c5fff45dc62164ff243a05d47fb8a3208035eb268974287e0aee8d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling ==1.27.0
    - pip
  run:
    - python >=3.8
    - securesystemslib >=1.0,<2.dev0
    - urllib3 <3,>=1.21.1

tests:
  - python:
      imports:
        - tuf
      pip_check: true

about:
  summary: A secure updater framework for Python
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - LICENSE-MIT
  homepage: https://www.updateframework.com
  repository: https://github.com/theupdateframework/python-tuf
  documentation: https://theupdateframework.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - travishathaway
